language: python
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
matrix:
  include:
    - name: "Check"
      python: 3.6
      env: TOXENV=check
    - name: "Python 2.7"
      python: 2.7
      env: TOXENV=2.7
    - name: "Python 3.4"
      python: 3.4
      env: TOXENV=3.4
    - name: "Python 3.5"
      python: 3.5
      env: TOXENV=3.5
    - name: "Python 3.6"
      python: 3.6
      env: TOXENV=3.6
    - name: "PyPy"
      python: pypy
      env: TOXENV=pypy
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always
